# Generated by Django 5.2.5 on 2025-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tecnologias_utilizadas', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='dailylog/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='dailylog/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='dailylog/')),
                ('link_publicacion_linkedin', models.URLField(blank=True, null=True)),
                ('link_ia_principal', models.URLField(blank=True, null=True)),
                ('link_ia_secundaria', models.URLField(blank=True, null=True)),
                ('link_ia_terciaria', models.URLField(blank=True, null=True)),
                ('link_respositorio', models.URLField(blank=True, null=True)),
                ('commit_principal', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
