# Generated by Django 5.2.5 on 2025-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='commit_principal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
