# Generated by Django 5.2.5 on 2025-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_ui', '0002_alter_dailylog_commit_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='project_name',
            field=models.CharField(default='Sin proyecto', max_length=100, verbose_name='Nombre del proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailylog',
            name='project_type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], default='frontend', max_length=20, verbose_name='Tipo de proyecto'),
            preserve_default=False,
        ),
    ]
