# Generated by Django 5.2.5 on 2025-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_ui', '0003_dailylog_project_name_dailylog_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='project_type',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], default='frontend', max_length=20, verbose_name='Tipo de proyecto'),
        ),
    ]
